### ISSUE TITLE
No module named 'pkg_resources'

### ISSUE THREAD

**Issue by rmharrison** [maxzheng/bumper#4]
```
$ pip3 install bumper 
# bump                                  
Traceback (most recent call last):
  File "/Users/.../.venv/bin/bump", line 5, in <module>
    from bumper import bump
  File "/Users/.../.venv/lib/python3.12/site-packages/bumper/__init__.py", line 6, in <module>
    from bumper.cars import RequirementsBumper, RequirementsManager, BumpAccident
  File "/Users/.../.venv/text-extract/lib/python3.12/site-packages/bumper/cars.py", line 3, in <module>
    import pkg_resources
```

**Comment by rmharrison** [comment]
I tried pip3 installing the missing import, but that failed too...
```
$ pip3 install pkg_resources
ERROR: Could not find a version that satisfies the requirement pkg_resources (from versions: none)
ERROR: No matching distribution found for pkg_resource
```

**Comment by maxzheng** [comment]
That was installed by default before Python 3.12. Now you have to manually install setuptools. I will add it to the requirement later. For now, can you try installing it manually and see if it works? 

```
pip3 install setuptools
```
